### ISSUE TITLE
Portable OpenJDK?

### ISSUE THREAD

**Issue by FranklinYu** [johanjanssen/ChocolateyPackages#1]
Currently OpenJDK isn't portable. Interested to make it portable?

**Comment by johanjanssen** [comment]
Hi, @franklinyu if I understand correctly the benefit of making it portable is that it can be installed without administrator rights, is that correct? I would be interested in it, do you know what I need to change to make it portable?

**Comment by johanjanssen** [comment]
Ok, in what directory will it be installed then? Sorry, I'm new to building Chocolatey packages :).

Yes, feel free to make a PR, thanks for your help!

**Comment by FranklinYu** [comment]
Closed by https://chocolatey.org/packages/openjdk.portable
