### ISSUE TITLE
Recommendation for dependency replacement for jre8 package?

### ISSUE THREAD

**Issue by teknowledgist** [johanjanssen/ChocolateyPackages#121]
Hi.  I am a fellow Chocolatey package maintainer, and I'm looking to change the jre8 dependencies of some packages to something without the licensing restrictions/questions that jre8 has.  

Since I know very little about Java and you are maintaining the vast majority of non-Oracle Java packages, I thought maybe you would have a suggestion for the "best" alternative dependency.  

Frankly, all the versions/varieties/flavors of java makes me very confused.  If you aren't comfortable making a suggestion, do you at least have a "simplified" reference where I (as distinctly NOT a Java developer) can evaluate the differences and make a decision?

Thanks!

**Comment by johanjanssen** [comment]
Hi, good question!

I'm not a legal expert, but I've found this explanation: https://dzone.com/articles/an-overview-on-jdk-vendors.

For Java 8 I have a couple of Chocolatey packages as an alternative for the Oracle one:
https://community.chocolatey.org/packages/Temurin8jre
https://community.chocolatey.org/packages/openjdk8jre
https://community.chocolatey.org/packages/liberica8jre

The best alternative is difficult to answer, some of them might have longer support, I don't know the details. But it should be relatively easy to switch from one to another. If I look at the number of downloads than openjdk8jre has the most, followed by temurin8jre (or actually adoptopenjdk8jre, which is succeeded by temurin8jre).

Some remarks:
- Temurin from Adoptium is the successor to AdoptOpenJDK
- Don't know if you need Java 8, but else I would recommend picking a Java 11 package
- If you want to stay on a specific version, make sure to use a package with a fixed id. For instance Temurin8jre, will always stay on Java 8 and only update the minor versions. Temurinjre will upgrade to the latest major and minor version.
- If you want to have the latest JRE and consider moving to Java 17, then Temurin might not be the best option as they probably won't make a JRE for 17

**Comment by teknowledgist** [comment]
Thanks for the prompt reply!  

I think I stumbled on that dzone article at some point about 2 years ago, but based on that and [this comment](https://www.reddit.com/r/java/comments/fm09d0/best_openjdk_java_11_for_various_platforms/fl1v3em), I would think more folks would choose either the Liberica or SAPmachine options.  Any ideas why those are less popular?

If I adopt Temurin8jre (for example), do I need to add any of the package params to the dependency or will a default install work basically the same as the default jre8?  (I'm not even sure the dependency tag in the nuspec has the value for that kind of option.)

**Comment by johanjanssen** [comment]
Adoptium's Temurin (the successor of AdoptOpenJDK) is also TCK verified: https://projects.eclipse.org/projects/adoptium/governance. Personally I started with AdoptOpenJDK, because it's more of a community project with multiple organizations supporting it. 

I don't know why the others are less popular, could be that some popular packages depend on the popular ones and thereby increase the number of downloads.

I'm not sure if all packages install the same elements as an Oracle JRE. Probably best to try it :-)

**Comment by teknowledgist** [comment]
One last question "theme" if you would be so kind...

What is the difference in general between the `jdk` flavors and the `jre` flavors?  For example, the [temurin8jre](https://community.chocolatey.org/packages/Temurin8jre), the [temurin8](https://community.chocolatey.org/packages/Temurin8} and the [temurinjre](https://community.chocolatey.org/packages/Temurinjre) all look really darn alike.  

If most folks using Java apps only need Java as a dependency to *run* (that's `jre`, "runtime", right?) and won't do any "development", where are all the `jre` releases of Java for v11, v16, etc.?  Everything for newer versions are `jdk`.

Thanks!

**Comment by johanjanssen** [comment]
jre is indeed the runtime environment and jdk the development environment. The jdk is much bigger in size, so if you only need to run something you should use the jre.

- termurin8jre will always stay on Java 8 and only receives minor updates
- temurinjre was planned to have the latest Java major version and the latest minor version
So if you want to stay on a specific major version of Java, then use a package with that version in the id.

However Temurin 11 jre is not working yet (0KB) and they [probably won't release jre's for 16 or later](https://github.com/adoptium/temurin-build/issues/2683).

If you want to use Java 11, then you can use liberica11jre, openjdk11jre or sapmachine11jre, or wait until Temurin fixes their download.
