### ISSUE TITLE
mvndaemon is now 0.7.1

### ISSUE THREAD

**Issue by jeffmaury** [johanjanssen/ChocolateyPackages#134]
But choco still show 0.7.0

https://github.com/johanjanssen/ChocolateyPackages/blob/c0e1aee8603b981f47eebd97d60f1f861706abcc/mvndaemon/mvndaemon.nuspec#L5

**Comment by johanjanssen** [comment]
Thanks for the heads up, I just pushed a new version of the package. Might take a while before it shows up due to automated and potentially some manual tests.
