### ISSUE TITLE
Update Corretto 8 JRE packages

### ISSUE THREAD

**Issue by lutkerd** [johanjanssen/ChocolateyPackages#149]
I am on the Corretto team and saw that the Corretto8 JRE wasn't updated to 332 and figured out why. Our release page now has the MSI's listed and it will be there going forward. Sorry about that.

We also publish a JSON on all of the latest releases https://github.com/corretto/corretto-downloads/blob/main/latest_links/indexmap_with_checksum.json. This will always have the latest stable build for every Corretto platform and version, it should be easier to parse and won't require special cases in your code when we do a new GitHub release that doesn't cover every platform.

**Comment by johanjanssen** [comment]
Thanks for the tip, I've also now changed the installer to use the MSI instead of the ZIP. Makes my configuration a bit cleaner as well. 

For now I made the changes manually, but indeed it's probably better to use the JSON. I didn't knew that one existed, so thanks for that one as well :).

**Comment by lutkerd** [comment]
Thanks! The JSON is pretty new, seems easier for package maintainers.
