### ISSUE TITLE
Update Corretto Q3 2022 release

### ISSUE THREAD

**Issue by caojoshua** [johanjanssen/ChocolateyPackages#159]
Hi, I'm from the Corretto team at Amazon. We have the following releases as of yesterday:

* https://github.com/corretto/corretto-8/releases
* https://github.com/corretto/corretto-11/releases
* https://github.com/corretto/corretto-17/releases
* https://github.com/corretto/corretto-18/releases

Can we get them updated in Chocolatey?

**Comment by johanjanssen** [comment]
Hi Joshua,

I'll try to update them in the coming days, thanks for the notification!

Kind regards,
Johan

Op wo 20 jul. 2022 om 22:55 schreef Joshua Cao ***@***.***>:

**Comment by johanjanssen** [comment]
Sorry for the delay, I was quite busy, I've pushed new packages. They are still under review.
