### ISSUE TITLE
Help with choco install ant?

### ISSUE THREAD

**Issue by cclauss** [johanjanssen/ChocolateyPackages#16]
__choco install [ant](https://github.com/AnthonyMastrean/chocolateypackages/tree/master/packages/ant)__ fails on Travis CI because it depends on __choco install [jre](https://github.com/proudcanadianeh/ChocoPackages/issues/28)__.  Would it be possible to create and alternate __ant__ that relies on a JRE that is compatible with Travis CI?

**Comment by johanjanssen** [comment]
You could, of course, create a separate ant package yourself. However, I think it would be better to ask if the maintainer would remove the dependency on Java. 

I've asked that same question for multiple Chocolatey packages with dependencies on jre/jdk's. Some removed it, others said they would remove it.

**Comment by cclauss** [comment]
Agreed.  AnthonyMastrean/chocolateypackages#346 should highlight the problem.

**Comment by johanjanssen** [comment]
Closing it here for now as it's not directly related to the packages I maintain.
