### ISSUE TITLE
Update jdk11 to 11.0.16.1

### ISSUE THREAD

**Issue by felfert** [johanjanssen/ChocolateyPackages#167]
Upstream has release a critical update fixing JDK-8279219:
See https://mail.openjdk.org/pipermail/jdk-updates-dev/2022-August/016645.html

Please upgrade on chocolatey as well

**Comment by johanjanssen** [comment]
Hi @felfert, thanks for your message. Which package are you using? I've updated most of them by now.

**Comment by felfert** [comment]
> Hi @felfert, thanks for your message. Which package are you using? I've updated most of them by now.

This one:
https://community.chocolatey.org/packages/openjdk11

**Comment by johanjanssen** [comment]
I got the OpenJDK builds (except for the latest version) from the AdoptOpenJDK upstream poject. Unfortunately that project is discontinued, see: https://adoptopenjdk.net/upstream.html. So I recommend using one of the other JDK builds such as Adoptium Temurin: https://community.chocolatey.org/packages/Temurin11.

I'm in the process of deprecating the OpenJDK Chocolatey packages.

**Comment by felfert** [comment]
What a pity. Thanks for the hint to the temurin packages.
