### ISSUE TITLE
AdoptOpenJDK Packages update via AU

### ISSUE THREAD

**Issue by RedBaron2** [johanjanssen/ChocolateyPackages#20]
@johanjanssen 
I'm wondering if you would be interested in updating your AdoptOpenJDK packages via AU?

**Comment by johanjanssen** [comment]
Hi @RedBaron2, I've quickly looked through the documentation for Automatic Package Updater. Updating packages automatically sounds interesting. However, I'm wondering, how can they find out if a new version is released? Or do you still have to provide the information before the update?

At the moment updating is relatively easy. Copying the download URL, checksum, version and finding out the folder in the zip file and rename it in the scripts. However, if it's possible to automate it further without making the configuration to difficult, I would definitely be interested.

**Comment by RedBaron2** [comment]
@johanjanssen 
> ...  However, I'm wondering, how can they find out if a new version is released? Or do you still have to provide the information before the update?

The package updater will either check the nuspec file for version, or it will store the versions inside a json file. AU compares the version(s) to the updated website parse.

> ... However, if it's possible to automate it further without making the configuration to difficult, I would definitely be interested.

I'm glad to hear you are receptive to automating your updating task. I made a update script for the `AdoptOpenJDK` package(s). You can take a look at the [code here](https://github.com/RedBaron2/development/tree/master/automatic/adoptopenjdk). Please take a look at it. The package name is changeable.

**Comment by johanjanssen** [comment]
> I'm glad to hear you are receptive to automating your updating task. I made a update script for the `AdoptOpenJDK` package(s). You can take a look at the [code here](https://github.com/RedBaron2/development/tree/master/automatic/adoptopenjdk). Please take a look at it. The package name is changeable.

Thanks a lot, I will definitely look at it! Probably next week as I'm quite busy with some other things.

**Comment by johanjanssen** [comment]
@RedBaron2 it looks cool and would make my life much easier thanks :).

Is it easy to add package with the latest release overall? Such as a package AdoptOpenJDK that contains the latest version. The same goes for AdoptOpenJDKJRE etc.

I like your package names better then mine :). However, I already have some packages released and they're being used. So I'd want to keep at least the names of those packages the same. Or if it's easier to stick to my (less nice) naming convention. I guess that shouldn't be too hard?

A list of my existing packages:
AdoptOpenJDK | adoptopenjdk | 12.0.1.12
AdoptOpenJDKOpenJ9JDK | adoptopenjdkopenj9jdk | 12.0.1.12
AdoptOpenJDKOpenJ9JRE | adoptopenjdkopenj9jre | 12.0.1.12
AdoptOpenJDKJRE | adoptopenjdkjre | 12.0.1.12
AdoptOpenJDK11JRE | adoptopenjdk11jre | 11.0.3.7
AdoptOpenJDK11 | adoptopenjdk11 | 11.0.3.7
AdoptOpenJDK8 | adoptopenjdk8 | 8.212.2
AdoptOpenJDK8JRE | adoptopenjdk8jre | 8.212

**Comment by RedBaron2** [comment]
> @RedBaron2 it looks cool and would make my life much easier thanks :).

I'm glad to help out.

> Is it easy to add package with the latest release overall? Such as a package AdoptOpenJDK that contains the latest version. The same goes for AdoptOpenJDKJRE etc.

Yes *

> I like your package names better then mine :). However, I already have some packages released and they're being used. So I'd want to keep at least the names of those packages the same. Or if it's easier to stick to my (less nice) naming convention. I guess that shouldn't be too hard?

Thank you. The naming of the packages is not a problem.  * The way we do this is to have a few meta packages. These packages will also auto update via AU , and as the main package is updated so will the meta(s). I will work on the `update.ps1` for the meta(s) in the next week.

> A list of my existing packages:
> AdoptOpenJDK | adoptopenjdk | 12.0.1.12
> AdoptOpenJDKOpenJ9JDK | adoptopenjdkopenj9jdk | 12.0.1.12
> AdoptOpenJDKOpenJ9JRE | adoptopenjdkopenj9jre | 12.0.1.12
> AdoptOpenJDKJRE | adoptopenjdkjre | 12.0.1.12
> AdoptOpenJDK11JRE | adoptopenjdk11jre | 11.0.3.7
> AdoptOpenJDK11 | adoptopenjdk11 | 11.0.3.7
> AdoptOpenJDK8 | adoptopenjdk8 | 8.212.2
> AdoptOpenJDK8JRE | adoptopenjdk8jre | 8.212

Thank you for the list. It will make getting the exact names easier.

**Comment by RedBaron2** [comment]
@johanjanssen It turns out that having the meta(s) are a good _idea_ , but in the current layout of chocolatey they are not worth it yet IMHO. I instead reworked the update file to change the package names to the ones already on Chocolatey. This works better and has less overhead. This one package downloads lots of data so I suggest you have it as a special run on Appveyor.

Just a note about in my testing. When the builds are built by AdoptOpen some builds may complete faster than others. I noticed this when the Java 8 build updated from version 8.0.212.03 to 8.0.212.04
The 64-bit  versions finished before the 32-bit versions. The AdoptOpen API caught the change and  when AU checked it updated the package. When the 32-bit versions finished being built (four days later) AU updated the package again to  8.0.212.4 not  8.0.212.04 even though the actual  build number is  8.0.212.04. 
This will be a rare occurrence and doesn't cause any problems with chocolatey or the package. 
I will work on a catch for such an occurrence for the future. The current version of the [code](https://github.com/RedBaron2/development/tree/master/automatic/adoptopenjdk) might have this slight error.

**Comment by johanjanssen** [comment]
Hi @RedBaron2 sorry for the really long delay. I was quite busy with family vacation (preparations).

I want to start using your scripts. Therefore I created a new GitHub repo as I think it's a bit easier to maintain and run automated tests with Travis. The repo is https://github.com/johanjanssen/AdoptOpenJDKChocolateyPackages. I've added your code in there.

I have a few questions for you:
- It seems AU needs to have a directory AdoptOpenJDK around the scripts for them to work? Currently, it doesn't work in my repo as it cannot find the nupkg file from AU. Is there a way to tell AU the nupkg file location?
- Currently, there is a different naming scheme, one for the packages I already maintain and one for the new ones. Although I still like your version scheme better, it's a bit confusing. I guess it's clearer and shortens the script if we use the same (old/less good) naming scheme for all packages?
- Are the README files needed? If a new version is added, without a README for that version then it causes errors. It seems we can go without them. If we use proper id's, the title's, etc. in the nuspec file then I think we can include simple generic description instead of all the separate README files.

Let me know what you think about my remarks. I've got some more time available now, so I can also make some changes/fixes.

**Comment by johanjanssen** [comment]
@RedBaron2 I've made quite some changes in the new repo. Such as the package id to lowercase (mandatory for Chocolatey) and the licenceurl version specific. I also made some of the changes I asked about in the previous post. If there is a good reason to keep it your way, I can still revert them. But for now I wanted to make some progress and get it up and running :).

If you want to make any changes please create a PR for the new repo, I think that's the easiest way to move forward quickly.

**Comment by johanjanssen** [comment]
I don't know if I messed up something. But when I have different versions installed and install a new one, it sometimes doesn't put the right version on the PATH. In my case an old version (a JRE, which shouldn't be on the PATH anyway).

**Comment by RedBaron2** [comment]
@johanjanssen 
The helper script from chocolatey will return the directory extracted to not the extracted directory from the zip AFAIR. I will double check anyways.

The issue of the readme files can be fixed so that certain words are replaced for each package. Ill have to work on that selective word replace. It would in turn make the readme file be two instead of multiple.

I'll look at the revised code soon. I will probably open a issue on the new repository.

**Comment by johanjanssen** [comment]
> Official recommendation is [AppVeyor](https://www.appveyor.com) although recently Travis also [starts to support Windows](https://blog.travis-ci.com/2018-10-11-windows-early-release).

Didn't knew that one yet, thank you for the link.

**Comment by johanjanssen** [comment]
@RedBaron2 I've changed your scripts to use the MSI installer instead of the zip. It also handles the PATH settings. I made the first packages with OpenJ9 based on your script. If they work well, I will use your scripts for all packages.

In the meantime, I'll close this issue. If there is something that needs to be done, please comment in the new repo: https://github.com/johanjanssen/AdoptOpenJDKChocolateyPackages

Thanks again!
