### ISSUE TITLE
Use installer for AdoptOpenJDK packages

### ISSUE THREAD

**Issue by FranklinYu** [johanjanssen/ChocolateyPackages#38]
From https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot#x64_win we see that AdoptOpenJDK actually provides installer (MSI files) besides Zip files. Is there any particular reason why use Zip instead of MSI files?

**Comment by johanjanssen** [comment]
I think the reason that I used zip files is that I started with OpenJDK and they only provided zip files. So I continued to use it for everything. MSI files are fine for me as well. However, I don't know how easy it is to uninstall the app and remove the JAVA_HOME and PATH settings when using an MSI.

**Comment by ExE-Boss** [comment]
In the case of MSI files, uninstallation is handled entirely by Windows, so it’s actually easier (you don't even need to provide an uninstall script, as the uninstall information is contained in the registry).

**Comment by johanjanssen** [comment]
@ExE-Boss but that means the users have to uninstall manually themselves? Or is it possible to uninstall the application when issuing 'choco uninstall [packagename]'?

**Comment by ExE-Boss** [comment]
Yes, it is possible to do `choco uninstall [packagename]`, this is in fact how nodejs.install is handled:
https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/nodejs.install/tools

**Comment by FranklinYu** [comment]
Note that if we use the installer, it would be optimal to enable the two optional feature “set `JAVA_HOME`” and “update registry entries”.

![screenshot](https://user-images.githubusercontent.com/7840192/56597220-4bd12700-65f2-11e9-912d-cef612bafc13.png)

(This screenshot is for Java 8 but other AdoptOpenJDK should be similar.)

Not sure how we do this through command-line argument.

**Comment by johanjanssen** [comment]
Looks good, if I have some more time, I will try to switch from zip to exe and perform some testing.

**Comment by johanjanssen** [comment]
I'm using the MSI installer in my automatic scripts: https://github.com/johanjanssen/AdoptOpenJDKChocolateyPackages

For now, I've released some OpenJ9 packages. If they work properly then I'll switch to MSI's for all AdoptOpenJDK packages except for version 9 and 10 as they only have ZIP files.
