### ISSUE TITLE
jre8 package

### ISSUE THREAD

**Issue by rgl** [johanjanssen/ChocolateyPackages#4]
Having an [AdoptOpenJRE8](https://adoptopenjdk.net/installation.html#x64_win-jre) package would also be good :-)

**Comment by johanjanssen** [comment]
Thanks for asking :): https://github.com/johanjanssen/ChocolateyPackages/tree/master/AdoptOpenJDK8JRE. I uploaded the package to Chocolatey and it's currently under review. So it should be there in a few days.

**Comment by johanjanssen** [comment]
It's listed now: https://chocolatey.org/packages/adoptopenjdk8jre
