### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by henryx** [johanjanssen/ChocolateyPackages#6]
Installation of OpenJDK 12 sets the `%PROGRAMFILES%\OpenJDK\jdk-12.0.0\bin` path, but files are in `%PROGRAMFILES%\OpenJDK\jdk-12`

**Comment by johanjanssen** [comment]
Sorry for that and thanks for mentioning it. I fixed it in a new version: choco install openjdk --version 12.0.0.1

**Comment by johanjanssen** [comment]
New version is approved and now available. Thanks again @henryx for the feedback!
