### ISSUE TITLE
AdoptOpenJDK8 bad install script

### ISSUE THREAD

**Issue by crumbl3d** [johanjanssen/ChocolateyPackages#9]
The script downloads the .msi instead of .zip and therefore it fails to install correctly leaving a mess inside C:\Program Files\AdoptOpenJDK\. Please fix it.

**Comment by cclauss** [comment]
@johanjanssen Would it be possible for Travis CI to spot these kind of problems?

**Comment by johanjanssen** [comment]
@cclauss yes I believe so. 

If we create a Chocolatey package with Travis based on the pull request it includes the URL. So if we try to install the package and check if java --version works it should fail if the URL is incorrect.

**Comment by crumbl3d** [comment]
@cclauss @johanjanssen Could it run the script to do something like this:
- check if the extension is .zip, then go to [openjdk8-binaries](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases) repo
- check the whether the specified name exists on that list
- finally check the corresponding hash there without downloading the file

**Comment by johanjanssen** [comment]
@crumbl3d that would also be possible. 

However, what we're working on now is to create a script that creates a chocolatey package if there is a pull request. That chocolatey package will be installed and then we check if java -version works. Under the hood that of course also checks if the file can be downloaded and if everything works correctly. 

We might add some more checks like checksums later.

**Comment by johanjanssen** [comment]
Thanks to @cclauss we now have automated builds with Travis that verify if the Chocolatey package can be installed and if `java -version` works. Hopefully, these measures will prevent mistakes like this. So I think this issue can be closed.

For more information see:
https://github.com/johanjanssen/ChocolateyPackages/blob/master/.travis.yml
https://github.com/johanjanssen/ChocolateyPackages/blob/master/.travis.ps1
